// Generated by https://quicktype.io

export interface usePokemonPaginatedResponse {
    count   : number;
    next    : string;
    previous: string;
    results : Result[];
}

export interface Result {
    name: string;
    url : string;
}

export interface SimplePokemon {
    id     :  string;
    name   :  string;
    picture:  string;
    color? :  string;
}
